chore(deps): update all (#659)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [eslint](https://eslint.org)
([source](https://togithub.com/eslint/eslint)) | [`8.55.0` ->
`8.56.0`](https://renovatebot.com/diffs/npm/eslint/8.55.0/8.56.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint/8.56.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint/8.56.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint/8.55.0/8.56.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint/8.55.0/8.56.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[eslint-plugin-security](https://togithub.com/eslint-community/eslint-plugin-security)
| [`2.0.0` ->
`2.1.0`](https://renovatebot.com/diffs/npm/eslint-plugin-security/2.0.0/2.1.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint-plugin-security/2.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint-plugin-security/2.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint-plugin-security/2.0.0/2.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint-plugin-security/2.0.0/2.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [pino-http](https://togithub.com/pinojs/pino-http) | [`8.5.1` ->
`8.6.0`](https://renovatebot.com/diffs/npm/pino-http/8.5.1/8.6.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/pino-http/8.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/pino-http/8.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/pino-http/8.5.1/8.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/pino-http/8.5.1/8.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [reflect-metadata](http://rbuckton.github.io/reflect-metadata)
([source](https://togithub.com/rbuckton/reflect-metadata)) | [`^0.1.14`
->
`^0.2.0`](https://renovatebot.com/diffs/npm/reflect-metadata/0.1.14/0.2.1)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/reflect-metadata/0.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/reflect-metadata/0.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/reflect-metadata/0.1.14/0.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/reflect-metadata/0.1.14/0.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>eslint/eslint (eslint)</summary>

### [`v8.56.0`](https://togithub.com/eslint/eslint/releases/tag/v8.56.0)

[Compare
Source](https://togithub.com/eslint/eslint/compare/v8.55.0...v8.56.0)

##### Features

-
[`0dd9704`](https://togithub.com/eslint/eslint/commit/0dd9704c4751e1cd02039f7d6485fee09bbccbf6)
feat: Support custom severity when reporting unused disable directives
([#&#8203;17212](https://togithub.com/eslint/eslint/issues/17212))
(Bryan Mishkin)
-
[`31a7e3f`](https://togithub.com/eslint/eslint/commit/31a7e3fde491e36496b54e8905c766b31162d776)
feat: fix no-restricted-properties false negatives with unknown objects
([#&#8203;17818](https://togithub.com/eslint/eslint/issues/17818)) (Arka
Pratim Chaudhuri)

##### Bug Fixes

-
[`7d5e5f6`](https://togithub.com/eslint/eslint/commit/7d5e5f68849ae80caec0fc96ecceebccd348deec)
fix: `TypeError: fs.exists is not a function` on read-only file system
([#&#8203;17846](https://togithub.com/eslint/eslint/issues/17846))
(Francesco Trotta)
-
[`74739c8`](https://togithub.com/eslint/eslint/commit/74739c849bbb6547b0e555ed8bb2ba1cbe0fdce4)
fix: suggestion with invalid syntax in no-promise-executor-return rule
([#&#8203;17812](https://togithub.com/eslint/eslint/issues/17812))
(Bryan Mishkin)

##### Documentation

-
[`9007719`](https://togithub.com/eslint/eslint/commit/90077199fe519953f9af8664bf947db4e4958514)
docs: update link in ways-to-extend.md
([#&#8203;17839](https://togithub.com/eslint/eslint/issues/17839)) (Amel
SELMANE)
-
[`3a22236`](https://togithub.com/eslint/eslint/commit/3a22236f8d10af8a5bcafe56092651d3d681c99d)
docs: Update README (GitHub Actions Bot)
-
[`54c3ca6`](https://togithub.com/eslint/eslint/commit/54c3ca6f2dcd2a7afd53f42fc32055a25587259e)
docs: fix migration-guide example
([#&#8203;17829](https://togithub.com/eslint/eslint/issues/17829))
(Tanuj Kanti)
-
[`4391b71`](https://togithub.com/eslint/eslint/commit/4391b71e62b15e54b0493f0dce1ea053ebbc0689)
docs: check config comments in rule examples
([#&#8203;17815](https://togithub.com/eslint/eslint/issues/17815))
(Francesco Trotta)
-
[`fd28363`](https://togithub.com/eslint/eslint/commit/fd2836342c2be4751b05fe0ba7cece17d1edecc8)
docs: remove mention about ESLint stylistic rules in readme
([#&#8203;17810](https://togithub.com/eslint/eslint/issues/17810))
(Zwyx)
-
[`48ed5a6`](https://togithub.com/eslint/eslint/commit/48ed5a6dad478a14d3e823f137455c523f373e0b)
docs: Update README (GitHub Actions Bot)

##### Chores

-
[`ba6af85`](https://togithub.com/eslint/eslint/commit/ba6af85c7d8ba55d37f8663aee949d148e441c1a)
chore: upgrade
[@&#8203;eslint/js](https://togithub.com/eslint/js)[@&#8203;8](https://togithub.com/8).56.0
([#&#8203;17864](https://togithub.com/eslint/eslint/issues/17864))
(Milos Djermanovic)
-
[`60a531a`](https://togithub.com/eslint/eslint/commit/60a531a9c0811ddf718e26b9136e133f580b6c36)
chore: package.json update for
[@&#8203;eslint/js](https://togithub.com/eslint/js) release (Jenkins)
-
[`ba87a06`](https://togithub.com/eslint/eslint/commit/ba87a0651a65b52c3ac442b512dd9f4c2b4c5f57)
chore: update dependency markdownlint to ^0.32.0
([#&#8203;17783](https://togithub.com/eslint/eslint/issues/17783))
(renovate\[bot])
-
[`9271d10`](https://togithub.com/eslint/eslint/commit/9271d10d9eabeafb0129a090f29191bfd14273c0)
chore: add GitHub issue template for docs issues
([#&#8203;17845](https://togithub.com/eslint/eslint/issues/17845)) (Josh
Goldberg ✨)
-
[`70a686b`](https://togithub.com/eslint/eslint/commit/70a686b3c1feac5eca98bbff9bd67175f550d5db)
chore: Convert rule tests to FlatRuleTester
([#&#8203;17819](https://togithub.com/eslint/eslint/issues/17819))
(Nicholas C. Zakas)
-
[`f3a599d`](https://togithub.com/eslint/eslint/commit/f3a599d34c7080fc0b2c9a60b5e54dc98c22867c)
chore: upgrade eslint-plugin-unicorn to v49.0.0
([#&#8203;17837](https://togithub.com/eslint/eslint/issues/17837)) (唯然)
-
[`905d4b7`](https://togithub.com/eslint/eslint/commit/905d4b75ab2df42aba30622cee0f66b511397e2c)
chore: upgrade eslint-plugin-eslint-plugin v5.2.1
([#&#8203;17838](https://togithub.com/eslint/eslint/issues/17838)) (唯然)
-
[`4d7c3ce`](https://togithub.com/eslint/eslint/commit/4d7c3ce246e6b499f472342ef59496a47cc033d6)
chore: update eslint-plugin-n v16.4.0
([#&#8203;17836](https://togithub.com/eslint/eslint/issues/17836)) (唯然)
-
[`fd0c60c`](https://togithub.com/eslint/eslint/commit/fd0c60c3be1f213e5a6d69d8a3248e963619e155)
ci: unpin Node.js 21.2.0
([#&#8203;17821](https://togithub.com/eslint/eslint/issues/17821))
(Francesco Trotta)

</details>

<details>
<summary>eslint-community/eslint-plugin-security
(eslint-plugin-security)</summary>

###
[`v2.1.0`](https://togithub.com/eslint-community/eslint-plugin-security/blob/HEAD/CHANGELOG.md#210-2023-12-15)

[Compare
Source](https://togithub.com/eslint-community/eslint-plugin-security/compare/v2.0.0...v2.1.0)

##### Features

- add config recommended-legacy
([#&#8203;132](https://www.togithub.com/eslint-community/eslint-plugin-security/issues/132))
([13d3f2f](https://www.github.com/eslint-community/eslint-plugin-security/commit/13d3f2fc6ba327c894959db30462f3fda0272f0c))

</details>

<details>
<summary>pinojs/pino-http (pino-http)</summary>

###
[`v8.6.0`](https://togithub.com/pinojs/pino-http/releases/tag/v8.6.0)

[Compare
Source](https://togithub.com/pinojs/pino-http/compare/v8.5.1...v8.6.0)

##### What's Changed

- Bump actions/setup-node from 3 to 4 by
[@&#8203;dependabot](https://togithub.com/dependabot) in
[https://github.com/pinojs/pino-http/pull/305](https://togithub.com/pinojs/pino-http/pull/305)
- fix: type variable for Logger by
[@&#8203;naseemkullah](https://togithub.com/naseemkullah) in
[https://github.com/pinojs/pino-http/pull/314](https://togithub.com/pinojs/pino-http/pull/314)

**Full Changelog**:
https://github.com/pinojs/pino-http/compare/v8.5.1...v8.6.0

</details>

<details>
<summary>rbuckton/reflect-metadata (reflect-metadata)</summary>

###
[`v0.2.1`](https://togithub.com/rbuckton/reflect-metadata/releases/tag/v0.2.1)

[Compare
Source](https://togithub.com/rbuckton/reflect-metadata/compare/v0.2.0...v0.2.1)

#### What's Changed

- Fix stack overflow crash in isProviderFor by
[@&#8203;rbuckton](https://togithub.com/rbuckton) in
[https://github.com/rbuckton/reflect-metadata/pull/155](https://togithub.com/rbuckton/reflect-metadata/pull/155)
- Update main to v0.2.1 by
[@&#8203;rbuckton](https://togithub.com/rbuckton) in
[https://github.com/rbuckton/reflect-metadata/pull/156](https://togithub.com/rbuckton/reflect-metadata/pull/156)

**Full Changelog**:
https://github.com/rbuckton/reflect-metadata/compare/v0.2.0...v0.2.1

###
[`v0.2.0`](https://togithub.com/rbuckton/reflect-metadata/releases/tag/v0.2.0):
reflect-metadata 0.2.0

[Compare
Source](https://togithub.com/rbuckton/reflect-metadata/compare/v0.1.14...v0.2.0)

#### What's Changed

- Add /lite and /no-conflict exports by
[@&#8203;rbuckton](https://togithub.com/rbuckton) in
[https://github.com/rbuckton/reflect-metadata/pull/144](https://togithub.com/rbuckton/reflect-metadata/pull/144)
- No dynamic evaluation in `/lite` mode by
[@&#8203;rbuckton](https://togithub.com/rbuckton) in
[https://github.com/rbuckton/reflect-metadata/pull/149](https://togithub.com/rbuckton/reflect-metadata/pull/149)

**Full Changelog**:
https://github.com/rbuckton/reflect-metadata/compare/v0.1.14...v0.2.0

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/UK-Export-Finance/mdm-api).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy45My4xIiwidXBkYXRlZEluVmVyIjoiMzcuOTMuMSIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Abhi Markan <abhi.markan@ukexportfinance.gov.uk>